// <auto-generated />
using System;
using System.Collections.Generic;
using AgroConnect.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroConnect.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008035242_AddHelpAlertsSpeech")]
    partial class AddHelpAlertsSpeech
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroConnect.Data.Entities.AlertSetting", b =>
                {
                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<bool>("DrySpell")
                        .HasColumnType("boolean")
                        .HasColumnName("dry_spell");

                    b.Property<bool>("HeavyRain")
                        .HasColumnType("boolean")
                        .HasColumnName("heavy_rain");

                    b.PrimitiveCollection<int[]>("PriceCrops")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("price_crops");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FarmerId")
                        .HasName("pk_alert_settings");

                    b.ToTable("alert_settings", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<Guid?>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("FarmerId")
                        .HasDatabaseName("ix_users_farmer_id");

                    b.HasIndex("PhoneE164", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_e164_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Farmer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AgeBand")
                        .HasColumnType("integer")
                        .HasColumnName("age_band");

                    b.Property<DateTimeOffset>("ClientUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_updated_at");

                    b.Property<string>("Community")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("community");

                    b.Property<DateTimeOffset>("ConsentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_at");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_given");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<int[]>("Crops")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("crops");

                    b.Property<int?>("DataPurchase")
                        .HasColumnType("integer")
                        .HasColumnName("data_purchase");

                    b.Property<decimal?>("FarmSize")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("farm_size");

                    b.Property<int>("FarmSizeUnit")
                        .HasColumnType("integer")
                        .HasColumnName("farm_size_unit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool?>("HasBankAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("has_bank_account");

                    b.Property<bool>("HasNoPhone")
                        .HasColumnType("boolean")
                        .HasColumnName("has_no_phone");

                    b.PrimitiveCollection<int[]>("HelpNeeded")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("help_needed");

                    b.PrimitiveCollection<int[]>("IncomeSources")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("income_sources");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<int?>("LastAgentVisit")
                        .HasColumnType("integer")
                        .HasColumnName("last_agent_visit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("LocationAccuracyMetres")
                        .HasColumnType("double precision")
                        .HasColumnName("location_accuracy_metres");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("MobileMoney")
                        .HasColumnType("integer")
                        .HasColumnName("mobile_money");

                    b.Property<string>("PhoneE164")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<int?>("PhoneType")
                        .HasColumnType("integer")
                        .HasColumnName("phone_type");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.PrimitiveCollection<int[]>("PlantingSeasons")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("planting_seasons");

                    b.PrimitiveCollection<int[]>("ReachChannels")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("reach_channels");

                    b.Property<string>("RegionDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region_district");

                    b.Property<Guid>("RegisteredById")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_id");

                    b.Property<DateTimeOffset>("ServerUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_updated_at");

                    b.Property<int?>("Soil")
                        .HasColumnType("integer")
                        .HasColumnName("soil");

                    b.HasKey("Id")
                        .HasName("pk_farmers");

                    b.HasIndex("PhoneE164")
                        .HasDatabaseName("ix_farmers_phone_e164");

                    b.HasIndex("RegisteredById", "ServerUpdatedAt")
                        .HasDatabaseName("ix_farmers_registered_by_id_server_updated_at");

                    b.ToTable("farmers", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.HelpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid?>("AnsweredById")
                        .HasColumnType("uuid")
                        .HasColumnName("answered_by_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Crop")
                        .HasColumnType("integer")
                        .HasColumnName("crop");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<bool>("HasVoiceNote")
                        .HasColumnType("boolean")
                        .HasColumnName("has_voice_note");

                    b.Property<Guid?>("OfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("officer_id");

                    b.Property<string>("Problem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("problem");

                    b.Property<DateTimeOffset?>("RemindedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VoiceSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("voice_seconds");

                    b.HasKey("Id")
                        .HasName("pk_help_requests");

                    b.HasIndex("AnsweredById")
                        .HasDatabaseName("ix_help_requests_answered_by_id");

                    b.HasIndex("FarmerId", "CreatedAt")
                        .HasDatabaseName("ix_help_requests_farmer_id_created_at");

                    b.HasIndex("OfficerId", "Status")
                        .HasDatabaseName("ix_help_requests_officer_id_status");

                    b.ToTable("help_requests", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.HelpVoiceNote", b =>
                {
                    b.Property<Guid>("HelpRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("help_request_id");

                    b.Property<byte[]>("Audio")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("audio");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.HasKey("HelpRequestId")
                        .HasName("pk_help_voice_notes");

                    b.ToTable("help_voice_notes", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.LoginCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_login_codes");

                    b.HasIndex("PhoneE164", "Role", "CreatedAt")
                        .HasDatabaseName("ix_login_codes_phone_e164_role_created_at");

                    b.ToTable("login_codes", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountPesewas")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_pesewas");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<int>("Network")
                        .HasColumnType("integer")
                        .HasColumnName("network");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<string>("ProviderMessage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("provider_message");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_reference");

                    b.HasIndex("FarmerId", "CreatedAt")
                        .HasDatabaseName("ix_payments_farmer_id_created_at");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("FarmerId")
                        .HasDatabaseName("ix_photos_farmer_id");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_photos_uploaded_by_id");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.SpeechClip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Audio")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("audio");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("text_hash");

                    b.Property<string>("Translated")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("translated");

                    b.HasKey("Id")
                        .HasName("pk_speech_clips");

                    b.HasIndex("Language", "TextHash")
                        .IsUnique()
                        .HasDatabaseName("ix_speech_clips_language_text_hash");

                    b.ToTable("speech_clips", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClientUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_updated_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.PrimitiveCollection<int[]>("Observations")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("observations");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("officer_id");

                    b.PrimitiveCollection<List<Guid>>("PhotoIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("photo_ids");

                    b.Property<DateOnly>("ScheduledFor")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset>("ServerUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_updated_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.PrimitiveCollection<int[]>("Topics")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("topics");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("FarmerId")
                        .HasDatabaseName("ix_visits_farmer_id");

                    b.HasIndex("OfficerId", "ServerUpdatedAt")
                        .HasDatabaseName("ix_visits_officer_id_server_updated_at");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<int>("Network")
                        .HasColumnType("integer")
                        .HasColumnName("network");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<string>("RecipientCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipient_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("FarmerId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_farmer_id");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.AlertSetting", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.Farmer", null)
                        .WithOne()
                        .HasForeignKey("AgroConnect.Data.Entities.AlertSetting", "FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_settings_farmers_farmer_id");
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.AppUser", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_farmers_farmer_id");
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Farmer", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_farmers_users_registered_by_id");
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.HelpRequest", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AnsweredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_help_requests_users_answered_by_id");

                    b.HasOne("AgroConnect.Data.Entities.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_help_requests_farmers_farmer_id");

                    b.HasOne("AgroConnect.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_help_requests_users_officer_id");
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.HelpVoiceNote", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.HelpRequest", null)
                        .WithOne()
                        .HasForeignKey("AgroConnect.Data.Entities.HelpVoiceNote", "HelpRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_help_voice_notes_help_requests_help_request_id");
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Payment", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_farmers_farmer_id");
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Photo", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_photos_farmers_farmer_id");

                    b.HasOne("AgroConnect.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_photos_users_uploaded_by_id");
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Visit", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visits_farmers_farmer_id");

                    b.HasOne("AgroConnect.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visits_users_officer_id");
                });

            modelBuilder.Entity("AgroConnect.Data.Entities.Wallet", b =>
                {
                    b.HasOne("AgroConnect.Data.Entities.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_farmers_farmer_id");
                });
#pragma warning restore 612, 618
        }
    }
}
